export const ACCESS_FETCHED = 'ACCESS_FETCHED'
export const ACCESS_GRANTED = 'ACCESS_GRANTED'
export const ACCESS_DENIED = 'ACCESS_DENIED'

export const GROUP_OPEN_TOGGLED = 'GROUP_OPEN_TOGGLED'
export const UPDATE_SIBLINGS = 'UPDATE_SIBLINGS'
export const OPEN_GROUP = 'OPEN_GROUP'
export const CLOSE_GROUP = 'CLOSE_GROUP'

export const DISPLAY_BUTTONS = 'DISPLAY_BUTTONS'
export const START_ADDING = 'START_ADDING'
export const FINISH_EDITING = 'FINISH_EDITING'
export const START_EDITING = 'START_EDITING'
